name: ESP-IDF Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up ESP-IDF
        uses: espressif/setup-esp-idf@v1
        with:
          version: v5.2

      - name: Build
        run: idf.py build
