name: ESP32 USB Mouse to BT Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ESP-IDF
      uses: espressif/setup-idf@v1
      with:
        version: v5.2

    - name: Build project
      run: idf.py build
