name: ESP32 Build Every Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          version: "v5.2"   # or whatever ESP-IDF version you want

      - name: Set project target
        run: idf.py set-target esp32s3

      - name: Build firmware
        run: idf.py build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/*.bin
            build/*.elf
            build/bootloader/*.bin
            build/partition_table/*.bin

