name: ESP32 IDF Build via Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with ESP-IDF (Docker)
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: latest        # ya da v6.0, v5.2 gibi tag
          target: esp32s3                # hedef board (esp32, esp32s3 vs.)
          path: .                        # proje kökü

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/*.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
