name: ESP32-S3 Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ESP-IDF
      uses: espressif/setup-esp-idf-action@v2
      with:
        version: v6.0

    - name: Install Python dependencies
      run: python -m pip install --upgrade pip

    - name: Build project
      run: idf.py build
      working-directory: S3-MACRO
