name: Build ESP32 Project

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Python setup
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # ESP-IDF setup
      - uses: esp-rs/setup-espidf@v2
        with:
          version: 'v6.0' # son ESP-IDF sürümü

      # Build
      - run: idf.py build

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
