name: ESP32 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up ESP-IDF
      uses: espressif/setup-esp-idf@v1
      with:
        version: v5.1

    - name: Build project
      run: idf.py build
